version: '2'
services:
  usb-camera :
    image: ros-docker-base
    environment:
     # ROS_IP: $ROS_IP
     # ROS_MASTER_URI: $ROS_MASTER_URI
      ROS_IP: 172.16.17.155
      ROS_MASTER_URI: "http://172.16.17.155:11311"
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
    stdin_open: true
    network_mode: host
    volumes:
      - $HOME/catkin_ws/src/exchange:/root/catkin_ws/src/exchange
      - $HOME/catkin_ws/src/usb_cam:/root/catkin_ws/src/usb_cam
      - $HOME/catkin_ws/src/image_common:/root/catkin_ws/src/image_common
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
    privileged: true
    devices:
    - /dev/bus/usb:/dev/bus/usb
    tty: true
    command: tail -f /dev/null 

